### ISSUE TITLE
Question about site navigation

### ISSUE THREAD

**Issue by Hopulent** [designfrontier/ask-me-anything#1]
Hi Daniel. I came across your blog and AMA today. I'm interested in learning more about your experiment with site navigation and discoverability. As suggested, my question is...What is your hypothesis and what were you trying to learn from the experiment?

**Comment by designfrontier** [comment]
@Hopulent I'll get this written up this afternoon :-)

**Comment by designfrontier** [comment]
cross posted on the site: http://www.designfrontier.net/design-and-the-internet-as-ephemera and also written up.

Thanks again for the question @Hopulent !
